### ISSUE TITLE
`sh: ./port-checker: Permission denied` when trying to run `port-checker` in `gluetun`

### ISSUE THREAD

**Issue by poperigby** [qdm12/port-checker#3]
I followed the steps from the `gluetun` wiki to check if my VPN server port was forwarded, and I'm getting the following error when trying to run the `port-checker` binary:
```
sh: ./port-checker: Permission denied
```

These are the steps I followed:
1. `docker exec -it gluetun sh`
2. `wget -qO port-checker https://github.com/qdm12/port-checker/releases/download/v0.1.0/port-checker_0.1.0_linux_amd64`
3. `chmod +x port-checker`
4. `./port-checker`

**Comment by qdm12** [comment]
That's strange. After you run `chmod +x port-checker`, try `echo $?` what does it give you? It should be `0` on success.

Alternatively try with `chmod 777 port-checker`? I'll try on my side later today.

**Comment by poperigby** [comment]
Okay this is strange. It's working now. Guess I just had to restart the container for some reason. Thanks.

**Comment by poperigby** [comment]
Now I have another problem, but I'll open a different issue.
