### ISSUE TITLE
Healthcheck errors when trying to run in `gluetun`

### ISSUE THREAD

**Issue by poperigby** [qdm12/port-checker#4]
I'm trying to run `port-checker` inside the `gluetun` container, but running it spams these errors over and over again:
```
2022/01/22 18:32:13 INFO healthcheck: listening on 127.0.0.1:9999
2022/01/22 18:32:13 ERROR healthcheck: listen tcp 127.0.0.1:9999: bind: address already in use
2022/01/22 18:32:13 INFO healthcheck: restarting
```
Running it with the `-port` flag doesn't change anything. It doesn't even seem to recognize it, because it keeps checking 9999.

**Comment by qdm12** [comment]
`-port` is not meant to do anything (let me know if documentation says otherwise).

You need to use `LISTENING_PORT=1234 ./port-checker` instead 😉

**Comment by poperigby** [comment]
Ahhh. The `gluetun` wiki says to use that, so that's why I was confused: https://github.com/qdm12/gluetun/wiki/VPN-server-port-forwarding#test-it

**Comment by poperigby** [comment]
Hmm. The `LISTENING_PORT` variable doesn't seem to affect it either. It's still checking 9999.

**Comment by qdm12** [comment]
There is no way to change it actually, I'll work on it.

In the meantime, you can change the health server address on Gluetun with `HEALTH_SERVER_ADDRESS=127.0.0.1:9998` for example.

**Comment by poperigby** [comment]
Thank you.

**Comment by qdm12** [comment]
The healthcheck got removed in the port-checker program since it was rather useless anyway. Closing this, and port-checker v0.2.0 will contain that change!
