### ISSUE TITLE
Be more verbose with the reply

### ISSUE THREAD

**Issue by Zorbatron** [qdm12/port-checker#5]
Currently, port-checker only responds with the client's source IP address. I think replying with the client's source port would be an interesting addition. Showing the port the port-checker is listening on would be cool too.

Right now it looks like this:
```
Client IP: 127.0.0.1
Browser: Firefox 119
Device: Computer
OS: Linux 0 
```

I'm imagining that it could look like this:
```
Listening Port: {Whatever port was set}
Client Address: {Source IP}:{Source Port}
Browser: Firefox 119
Device: Computer
OS: Linux 0 
```

And in the future if there's an option to specify a listening address instead of `0.0.0.0` and `::`, the listening port could be changed to listening address and show the IP:Port combo.

**Comment by qdm12** [comment]
- listening address returned from commit ee6fe6fb5f9d1cbc27241b18c9d1acf267932284
- client address (ip + port) returned from commit d6c661dae5e204415b166414eeab0adc18a5a343 - not always, it's just an IP address for forwarded/proxied http requests
- you can specify the listening address with `LISTENING_ADDRESS` from commit 4036f4069dbe6188887ff505cf458d1c4438035c
